### ISSUE TITLE
Pain Points of Tedana Meta-Issue

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#383]
### Summary
We'll list common points of frustration or confusion here ahead of our hackathon

### Running List
- [ ] How to run

**Comment by emdupre** [comment]
- [ ] How to run from the fMRIPrep working directory
- [ ] How to run from AFNI proc
- [ ] How to incorporate fieldmap corrections appropriately
- [ ] Memory issues in running tedana
- [ ] Changing the default PCA denoising ?

**Comment by smoia** [comment]
- Debug PCA denoising
- Have a look at the elbow code for its PCA application
- Get a general background of the ME maths related to the code

**Comment by dowdlelt** [comment]
- [ ] using tedana after/with other software (SPM comes to mind)
- [ ] degrees of freedom after tedana
- [ ] using tedana regressors seperately

**Comment by jbteves** [comment]
@handwerkerd anything missing?

**Comment by handwerkerd** [comment]
- [ ] How to figure out if denoising ran correctly (i.e. easy summary stats)
- [ ] How to figure out what can be run better, if the summary stats show an issue
- [ ] How to decide which options to use
- [ ] How to denoise across multiple runs during one session, across sessions/subjects
- [ ] What steps to do before vs after denoising (i.e motion & distortion corrections)
- [ ] Integrating recorded respiratory and physiological information into multi-echo denoising

**Comment by dowdlelt** [comment]
As post-tedana steps are developled (#344) I imagine they will add an additional, but user-desired, level of complexity so 
- [ ] How to use knowledge (motion estimates, maps) for component refinement

**Comment by jbteves** [comment]
I'm actually going to break the mold and add a developer point of frustration:
- [ ] Running and modifying tests

**Comment by dowdlelt** [comment]
An additional one related to figures, 

[ ] check orientation of brain/acquisition when making multiplanar cuts - rotate to normal. 

Sometimes with R-L acquisitions the brain is flipped on its side, coronal isn't coronal, etc - That just adds a bit of frustration (and possible confusion) when inspecting output. May be an easy fix...

**Comment by dowdlelt** [comment]
And thought of another thing: the errors that pop up during running (not due credit, we know about that...). maybe these are environment specific, but they always worry me...

- [ ] runtimes errors that cause confusion and concern

examples:
```
RuntimeWarning: divide by zero encountered in true_divide
  F_S0 = (alpha - SSE_S0) * (n_echos - 1) / (SSE_S0)

INFO:tedana.metrics.kundu_fit:Performing spatial clustering of components
INFO:tedana.selection.tedica:Performing ICA component selection with Kundu decision tree v2.5
/home/stone-ext4/logan/.local/lib/python3.6/site-packages/tedana/selection/tedica.py:244: RuntimeWarning: invalid value encountered in double_scalars
  np.min(comptable.loc[acc_prov, 'variance explained'])))
```

**Comment by jbteves** [comment]
@dowdlelt FYI we've discussed a little bit about duecredit specifically [in the now-closed #196](https://github.com/ME-ICA/tedana/issues/196). @tsalo at some point added the note that it doesn't impact package functionality.

**Comment by dowdlelt** [comment]
yeah, duecredit doesn't bother me at all, because it has the note and such - it is the other warnings while the package is running that are a bit more confusing. If users see problems in output, have trouble running, etc - then it would be natural for them to assume that these problems could be coming from the issues they see during code execution.

**Comment by jbteves** [comment]
Ack, sorry, I misread the above. I agree that we should fix the other warnings.

**Comment by smoia** [comment]
[] Add a check on volumes and TE input order

**Comment by tsalo** [comment]
This has been untouched for three years now. Can we update our pain points (I assume at least some have been addressed) and break this up into separate issues?

**Comment by tsalo** [comment]
I think we have either addressed or opened separate issues for each of the pain points brought up in this issue, so I'm going to close it.
